### ISSUE TITLE
Use EIP-1167

### ISSUE THREAD

**Issue by osarrouy** [argentlabs/argent-contracts#51]
Hi guys,

I was having a look at your codebase and was wondering if you were considering using [EIP-1167](https://eips.ethereum.org/EIPS/eip-1167) as a proxy for Argent’s wallets.

EIP-1167 is becoming a widely use standard and it may optimize gas costs and provide interesting network-effect advantages [like Etherscan automatically linking to the implementation].

As your current proxy does not allow to upgrade the implementation address anyhow that would be a perfect fit. 

Just my two cents :)

**Comment by elenadimitrova** [comment]
This is indeed a valid suggestion, thanks for that and sorry it's taken a year to respond! We are still using the Proxy contract for wallets partly because of the additional event we fire in the `Received` fallback function but also because we're experimenting with an implementation-upgradable proxy for the wallet which is more complex than then minimal version the EIP offers. Granted that none of these arguments existed when you proposed it so thanks again for that.
